contact_links:
  - name: 📖 Documentation
    url: https://nuxtseo.com/robots
    about: Check the documentation for guides and examples.
  - name: 💬 Harlan's Discord Server
    url: https://discord.com/invite/5jDAMswWwX
    about: Join the friendly discord server for help with your issue.
